# modules/ai_engine.py
import google.generativeai as genai
import streamlit as st
import os

def configure_gemini():
    try:
        api_key = st.secrets["GEMINI_API_KEY"]
        genai.configure(api_key=api_key)
        return True
    except Exception as e:
        st.error(f"Gemini 配置失敗: {e}")
        return False

def generate_ppt_content(topic, uploaded_files):
    if not configure_gemini():
        return "配置錯誤，無法生成。"
    
    # 這是我們的策略：優先用 Pro，不行就用 Flash，再不行用老版 Pro
    # 這樣可以保證絕對不會因為模型名字報錯
    model_list = [
        "gemini-1.5-pro", 
        "gemini-1.5-flash", 
        "gemini-1.5-pro-latest",
        "gemini-pro"
    ]
    
    # 構建 Prompt
    prompt = f"""
    你的身份：清華大學入學考試語文輔導專家。
    任務：閱讀提供的教材資料，為主題「{topic}」製作一份講課用的幻燈片代碼。
    工具：Marp (Markdown Presentation)。
    
    要求：
    1. **排版**：必須包含 Marp 標頭 (theme: gaia)。
    2. **結構**：
       - 封面、目錄。
       - **核心知識點**：提取重點。
       - **易錯點辨析**：結合清華考試特點。
       - 真題/例題演練。
       - 課堂總結。
    3. **輸出**：僅輸出 Markdown 源代碼。
    """
    
    content_parts = [prompt]
    
    # 處理圖片/PDF
    if uploaded_files:
        for file in uploaded_files:
            content_parts.append({
                "mime_type": file.type,
                "data": file.getvalue()
            })
            
    # --- 核心修改：輪詢嘗試機制 ---
    last_error = ""
    
    for model_name in model_list:
        try:
            # 顯示當前正在嘗試哪個模型（方便我們調試）
            print(f"正在嘗試模型: {model_name}...") 
            model = genai.GenerativeModel(model_name)
            
            # 這裡不顯示 loading spinner，因為 app.py 那邊已經有了
            response = model.generate_content(content_parts)
            
            # 如果成功，直接返回結果，並在結果前標註用了哪個模型
            return f"<!-- Generated by {model_name} -->\n{response.text}"
            
        except Exception as e:
            # 如果失敗，記錄錯誤，然後繼續循環嘗試下一個
            print(f"模型 {model_name} 失敗: {e}")
            last_error = str(e)
            continue
            
    # 如果循環結束還沒返回，說明所有模型都掛了
    return f"生成徹底失敗。已嘗試模型 {model_list}。\n最後一次報錯: {last_error}"
